name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:

  # Build the image
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name:
        run: |
          echo "REF_NAME=${GITHUB_REF_NAME}"
          echo "REF=${GITHUB_REF}"
          echo "VERSION=${GITHUB_REF_NAME}"
      - run: docker build -t myapp:test .
  # Test the image
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run tests"
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-2"
  test3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-3"
  # Push image
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Push image to docker registry"
