name: Docker CI

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  # Build the image
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
       
      #- name: Debug
      #  run: echo "VERSION=$GITHUB_REF_NAME"
          
      - name: build and tag
        run: |
          docker build -t fasilcv/myapp:"${VERSION}" .
          docker tag fasilcv/myapp:"${VERSION}" myapp:latest
  # Test the image
  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run tests"
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-2"
  test3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-3"
  # Push image
  push:
    needs: [ test1, test3 ]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Image push 
        run: echo "Push image to docker registry"
