name: Docker CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Build the image
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: docker build -t fasilcv/myapp:local .
      - name: save image
        run: docker save -o myapp.tar fasilcv/myapp:local

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: myapp.tar
  
  # Test jobs
  test1-docker-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - run: ls -lh
      - run: docker load -i myapp.tar
      - run: echo "Run tests"
      
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-2"
  test3:
    needs: test2
    runs-on: ubuntu-latest
    steps:
      - run: echo "test-3"

